default: &default
  adapter: mysql2
  encoding: utf8
  #pool: 5
  username: root
  password:
  host: localhost

development:
  <<: *default
  database: sale_controls_development

test:
  <<: *default
  database: sale_controls_test

production:
  <<: *default
  database: sale_controls_production
